POST https://localhost:8443/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}
# Bearer

###
POST http://localhost:4001/carts
Content-Type: application/json

{
  "customer": {
    "id": 1,
    "name": "khaled"
  },
  "products":[
    {
      "name": "monsttre",
      "description": "khlajjj"
    }
  ]
}
###
GET http://localhost:4001/carts/61cb7202608839424b7d0a80/customer
Content-Type: application/json
###
