App\Entity\User:
  collectionOperations:
    get:
    users:
      path: /users
      method: POST
      controller: App\Controller\CustomerCreateController
    admins:
      path: /amdins
      method: POST
      controller: App\Controller\AdminCreateController
    userConnected:
      method: GET
      path: /users/connected
      controller: App\Controller\UserConnectedController
      pagination_enabled: false

     
 