App\Entity\User:
  collectionOperations:
    get:
    customers:
      path: /customers
      method: POST
      controller: App\Controller\CustomerCreateController
    admins:
      path: /amdins
      method: POST
      controller: App\Controller\AdminCreateController
    providers:
      path: /providers
      method: POST
      controller: App\Controller\ProviderCreateController
    userConnected:
      method: GET
      path: /users/connected
      controller: App\Controller\UserConnectedController
      pagination_enabled: false

     
 