App\Entity\User:
  attributes:
    denormalization_context:
      groups: ['write:customer:user']
  collectionOperations:
    get: ~
    customers:
      path: /customers
      method: POST
      controller: App\Controller\CustomerCreateController
    admins:
      path: /amdins
      method: POST
      controller: App\Controller\AdminCreateController
    providers:
      path: /providers
      method: POST
      controller: App\Controller\ProviderCreateController

App\Entity\Request:
  attributes:
    normalization_context:
      groups: ['read:customer:item','read:request:collection']
    denormalization_context:
      groups: [write:request:collection]
  collectionOperations:
     get: ~
     post:
      security_post_denormalize: 'is_granted("REQUEST_CREATE",object)'
      security_message: 'only customers can create requests.'
  itemOperations:
    get: ~
    delete:
      security: 'is_granted("REQUEST_DELETE",object)'
      security_message: 'only customer how create this request can delete him.'
    put:
      denormalization_context:
        groups: [edit:request:item]
      security: 'is_granted("REQUEST_EDIT",object)'
      security_message: 'only customer how create this request can edit him.'


 
   

     
 